// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiuvVXedyEK-bi_ZYP5UJm9CWjOzOrgfY',
    appId: '1:627324944723:web:6a2938eb35326df64da1a6',
    messagingSenderId: '627324944723',
    projectId: 'uts-flutter-mrgemini-app',
    authDomain: 'uts-flutter-mrgemini-app.firebaseapp.com',
    storageBucket: 'uts-flutter-mrgemini-app.firebasestorage.app',
    measurementId: 'G-0HTNPM37Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIAmv_wkIA1KD3hyZPesQXyNMOsPP2_ac',
    appId: '1:627324944723:android:b8b498e3d99a99bf4da1a6',
    messagingSenderId: '627324944723',
    projectId: 'uts-flutter-mrgemini-app',
    storageBucket: 'uts-flutter-mrgemini-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOi-GTlPW73t-6sH_GJ-fGYZOEU009Nx4',
    appId: '1:627324944723:ios:f805199668775ea74da1a6',
    messagingSenderId: '627324944723',
    projectId: 'uts-flutter-mrgemini-app',
    storageBucket: 'uts-flutter-mrgemini-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUjicobauts2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOi-GTlPW73t-6sH_GJ-fGYZOEU009Nx4',
    appId: '1:627324944723:ios:f805199668775ea74da1a6',
    messagingSenderId: '627324944723',
    projectId: 'uts-flutter-mrgemini-app',
    storageBucket: 'uts-flutter-mrgemini-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUjicobauts2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiuvVXedyEK-bi_ZYP5UJm9CWjOzOrgfY',
    appId: '1:627324944723:web:24b3bdaf725303a94da1a6',
    messagingSenderId: '627324944723',
    projectId: 'uts-flutter-mrgemini-app',
    authDomain: 'uts-flutter-mrgemini-app.firebaseapp.com',
    storageBucket: 'uts-flutter-mrgemini-app.firebasestorage.app',
    measurementId: 'G-D0PBFM8B27',
  );
}
